# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upuai < Formula
  desc "Upuai Cloud CLI — deploy your apps with a single command."
  homepage "https://upuai.cloud"
  version "0.27.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.27.0/upuai_0.27.0_darwin_x86_64.tar.gz"
      sha256 "c7e8573680e660d42ebcb1be3e4159238452d8db9370005f4d8e4b43f565e490"

      define_method(:install) do
        bin.install "upuai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.27.0/upuai_0.27.0_darwin_arm64.tar.gz"
      sha256 "c2f47808e8569536030ac436c22c3cddb97d397c38cec8d7cc7565bef193cbfc"

      define_method(:install) do
        bin.install "upuai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.27.0/upuai_0.27.0_linux_x86_64.tar.gz"
      sha256 "42d9aca4fb72b3b0ba218fd0e3641101db0323c5e1909cda4ea04a72edf04423"
      define_method(:install) do
        bin.install "upuai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.27.0/upuai_0.27.0_linux_arm64.tar.gz"
      sha256 "1c538c16f21038a7468aa5974b2e201e5f03aad20aafff73aefe83483b043198"
      define_method(:install) do
        bin.install "upuai"
      end
    end
  end

  test do
    system "#{bin}/upuai", "version"
  end
end
