# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upuai < Formula
  desc "Upuai Cloud CLI — deploy your apps with a single command."
  homepage "https://upuai.cloud"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.19.0/upuai_0.19.0_darwin_x86_64.tar.gz"
      sha256 "0338ea569326895ca92de5b9d204835f8531de6be386adec7871093ec1477dc3"

      define_method(:install) do
        bin.install "upuai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.19.0/upuai_0.19.0_darwin_arm64.tar.gz"
      sha256 "7de5c63e7ad2270c5d5af1ed8b5d454a4be0c748a24a3ac4fec64d987b1c01de"

      define_method(:install) do
        bin.install "upuai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.19.0/upuai_0.19.0_linux_x86_64.tar.gz"
      sha256 "c27ac0a37942d6edc6891654c2013061f00792b494b6debb340818b54a6d2974"
      define_method(:install) do
        bin.install "upuai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.19.0/upuai_0.19.0_linux_arm64.tar.gz"
      sha256 "aedf61375c80b830aac90bf70aa1d40ca8e325cfd3b2a5b15714023b56ed1448"
      define_method(:install) do
        bin.install "upuai"
      end
    end
  end

  test do
    system "#{bin}/upuai", "version"
  end
end
