# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upuai < Formula
  desc "Upuai Cloud CLI — deploy your apps with a single command."
  homepage "https://upuai.cloud"
  version "0.21.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.21.0/upuai_0.21.0_darwin_x86_64.tar.gz"
      sha256 "bde7b463571258f636a000b192f5636ad4a3dc9d5278de8800a5a4e201095fe2"

      define_method(:install) do
        bin.install "upuai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.21.0/upuai_0.21.0_darwin_arm64.tar.gz"
      sha256 "23fbeed4549756c5a18286e6dbd1cbe0c3e64d57fb0a94bcaa140ff1bb9ee08e"

      define_method(:install) do
        bin.install "upuai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.21.0/upuai_0.21.0_linux_x86_64.tar.gz"
      sha256 "91f3a47a8b0716255cbee6f86ee72cf91dc406e87f387f23b21be27c44f3cd9f"
      define_method(:install) do
        bin.install "upuai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saiph-ti/upuai-cli/releases/download/v0.21.0/upuai_0.21.0_linux_arm64.tar.gz"
      sha256 "960916d6ccf926f48fcbbe5f6bd1ba2d33fc196f9bc7c0b68432c5b2fc03f3c9"
      define_method(:install) do
        bin.install "upuai"
      end
    end
  end

  test do
    system "#{bin}/upuai", "version"
  end
end
